app.constant('Permicao', {
    cargos: '1',
    clientes: '2',
    clientes_endereco: '3',
    compras: '4',
    compras_itens: '5',
    financeiros_entradas: '6',
    financeiros_saidas: '7',
    fornecedores: '8',
    fornecedores_enderecos: '9',
    funcionarios: '10',
    funcionarios_enderecos: '11',
    grupos: '12',
    grupos_permissoes: '13',
    marcas:'14',
    modelos:'15',
    modulos:'16',
    permissoes:'17',
    reparos:'18',
    tipo_reparos:'19',
    tipo_veiculos:'20',
    usuarios:'21',
    usuarios_grupos:'22',
    veiculos:'23',
    vendas:'24',
    vendas_itens:'25'
});